CREATE SEQUENCE HIBERNATE_SEQUENCE AS INTEGER START WITH 1
CREATE TABLE student
  (id BIGINT PRIMARY KEY,
  surname VARCHAR(50),
  name VARCHAR(50),
  patronymic VARCHAR(50),
  birthday TIMESTAMP,
  phone VARCHAR(12),
  photo VARCHAR(255),
  have_license BOOLEAN,
  basic_path VARCHAR(255));
ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART WITH 2